basic_settings:
  site_title: CAAD.XYZ
  site_tagline: focus on computer-based architectural design
  favicon_image: /assets/images/favicon.png

header_settings:
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Posts'
      url: '/'
    - title: 'About'
      url: '/about'

social_settings:
  facebook_url: 'https://www.facebook.com/Caadxyz-105995454484474'
  twitter_url: ''
  instagram_url: ''
  youtube_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  github_url: 'https://github.com/caadxyz'
  kickstarter_url: ''
  jp_url: '/category/jp'
  zh_url: '/category/zh'
  en_url: '/category/en'
  spotify_url: ''
  linkedin_url: ''

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
gh_api:
  # ci: f9afa028440c75779c6c
  # cs: 24ba96b011dc6ec70741414e14c8f317b0553034
